### ISSUE TITLE
Does this work with non conventional delimiters ?

### ISSUE THREAD

**Issue by blaquans** [edwindj/chunked#1]
Very often, I've to deal with non conventional delimiters such as "|", "#"  or "¥" . I think it would be reall useful to implement `read_delim_chunkwise()`

**Comment by edwindj** [comment]
Thanks for the suggestion! 
It is possible to specify a delimiter in  `read_chunkwise`, `read_csv_chunkwise`, `read_table_chunkwise` with the `sep` parameter.

This should work, but I did not check (yet)
```
chunked_file <- read_chunkwise("file_in.txt", sep="|")
```

**Comment by blaquans** [comment]
ok fine
