### ISSUE TITLE
Can't read csvs with NAs in numeric columns

### ISSUE THREAD

**Issue by mbsabath** [edwindj/chunked#12]
When reading data stored as a csv with NAs in a numeric column this error is returned:

```
Error in .local(x, ...) : 
Conversion to double failed; line=1; column=17; string='NA'
```
I'm experimenting with trying to use mutate to force the NA to be read as missing, I'll update the issue if I find a work around.

**Comment by mbsabath** [comment]
Seems like the `ignore_failed_conversion` flag in laf could be used to handle this pretty easily

**Comment by mbsabath** [comment]
Documenting my workaround here:

Generating my own LaF object seemed to solve the problem:

```R
file1 <- "foo.csv"
f1 <- LaF::laf_open(LaF::detect_dm_csv(file1, header = T), ignore_failed_conversion = T)
f1 <- read_chunkwise(f1)

**Comment by edwindj** [comment]
Thanks for reporting both the issue and the work-around!
