### ISSUE TITLE
Support for fst format

### ISSUE THREAD

**Issue by xiaodaigh** [edwindj/chunked#6]
It would be great to extend dplyr support to [fst(https://github.com/fstpackage/](https://github.com/fstpackage/fst) format which is fast and can be read in chunked (possibly processed in parallel).

**Comment by xiaodaigh** [comment]
I made a package, disk.frame, to support fst backend see http://diskframe.com

**Comment by edwindj** [comment]
Nice! I still plan to add a fst/disk.frame interface :-)

Op za 24 aug. 2019 06:19 schreef evalparse <notifications@github.com>:
